/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';

export default function Building({ ...props }) {
  const { nodes, materials } = useSpline(
    'https://prod.spline.design/q3SrPhJqc-P8bApm/scene.splinecode'
  );
  return (
    <>
      <color attach="background" args={['#5a555d']} />
      <group {...props} dispose={null}>
        <mesh
          name="Cube 23"
          geometry={nodes['Cube 23'].geometry}
          material={materials.statue}
          castShadow
          receiveShadow
          position={[62.35, 66, -272.92]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube 22"
          geometry={nodes['Cube 22'].geometry}
          material={materials.statue}
          castShadow
          receiveShadow
          position={[0.21, 66.55, -269.63]}
        />
        <mesh
          name="Cube 21"
          geometry={nodes['Cube 21'].geometry}
          material={materials['Cube 21 Material']}
          castShadow
          receiveShadow
          position={[29.92, 22.8, -275.33]}
        />
        <group
          name="tree 11"
          position={[2349.06, 551.41, 528.14]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.51]}
        >
          <mesh
            name="Cylinder 4"
            geometry={nodes['Cylinder 4'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 3"
            geometry={nodes['Cylinder 3'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 2"
            geometry={nodes['Cylinder 2'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 10"
          position={[2225.65, 533.62, 232.36]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.51]}
        >
          <mesh
            name="Cylinder 41"
            geometry={nodes['Cylinder 41'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 31"
            geometry={nodes['Cylinder 31'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 21"
            geometry={nodes['Cylinder 21'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder1"
            geometry={nodes.Cylinder1.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 9"
          position={[2083.21, 528.48, -38.04]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.51]}
        >
          <mesh
            name="Cylinder 42"
            geometry={nodes['Cylinder 42'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 32"
            geometry={nodes['Cylinder 32'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 22"
            geometry={nodes['Cylinder 22'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder2"
            geometry={nodes.Cylinder2.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 8"
          position={[1827.08, 497.83, -1113.74]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.51]}
        >
          <mesh
            name="Cylinder 43"
            geometry={nodes['Cylinder 43'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 33"
            geometry={nodes['Cylinder 33'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 23"
            geometry={nodes['Cylinder 23'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder3"
            geometry={nodes.Cylinder3.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 7"
          position={[1827.08, 513.68, -850.11]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.51]}
        >
          <mesh
            name="Cylinder 44"
            geometry={nodes['Cylinder 44'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 34"
            geometry={nodes['Cylinder 34'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 24"
            geometry={nodes['Cylinder 24'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder4"
            geometry={nodes.Cylinder4.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 6"
          position={[-900.88, 1354.64, -766.12]}
          rotation={[-0.04, 0, -0.04]}
          scale={[0.63, 0.65, 0.63]}
        >
          <mesh
            name="Cylinder 45"
            geometry={nodes['Cylinder 45'].geometry}
            material={materials.trunk}
            castShadow
            receiveShadow
            position={[-0.91, -195.38, 1.19]}
            scale={[0.1, 1.59, 0.1]}
          />
          <mesh
            name="Cylinder 35"
            geometry={nodes['Cylinder 35'].geometry}
            material={materials['tree red']}
            castShadow
            receiveShadow
            position={[14.29, 191, 0]}
            rotation={[0, 0, -0.07]}
            scale={[0.56, 1.05, 0.56]}
          />
          <mesh
            name="Cylinder 25"
            geometry={nodes['Cylinder 25'].geometry}
            material={materials['tree red']}
            castShadow
            receiveShadow
            position={[1.12, -14.3, 0]}
            rotation={[0, 0, -0.03]}
            scale={[0.56, 1.05, 0.56]}
          />
          <mesh
            name="Cylinder5"
            geometry={nodes.Cylinder5.geometry}
            material={materials['tree red']}
            castShadow
            receiveShadow
            position={[-1.71, -237.92, 0]}
            rotation={[0, 0, -0.01]}
            scale={[0.56, 1.05, 0.56]}
          />
        </group>
        <mesh
          name="Shape 32"
          geometry={nodes['Shape 32'].geometry}
          material={materials['Shape 32 Material']}
          castShadow
          receiveShadow
          position={[388.25, 273.46, -569.52]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 31"
          geometry={nodes['Shape 31'].geometry}
          material={materials['Shape 31 Material']}
          castShadow
          receiveShadow
          position={[290.14, 274.54, -382.78]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 30"
          geometry={nodes['Shape 30'].geometry}
          material={materials['Shape 30 Material']}
          castShadow
          receiveShadow
          position={[127.05, 185.36, -615.09]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 29"
          geometry={nodes['Shape 29'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[382.22, 165.23, -155.4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          name="tree 5"
          position={[95.55, 235.04, -1139.93]}
          rotation={[-0.06, 0, 0.04]}
          scale={[0.62, 0.73, 0.62]}
        >
          <mesh
            name="Cylinder 46"
            geometry={nodes['Cylinder 46'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 36"
            geometry={nodes['Cylinder 36'].geometry}
            material={materials['tree orange']}
            castShadow
            receiveShadow
            position={[-12.23, 47.39, 0]}
            rotation={[0, 0, -0.01]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 26"
            geometry={nodes['Cylinder 26'].geometry}
            material={materials['tree orange']}
            castShadow
            receiveShadow
            position={[-11.83, -116.7, 0]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder6"
            geometry={nodes.Cylinder6.geometry}
            material={materials['tree orange']}
            castShadow
            receiveShadow
            position={[-10.06, -271.33, 0]}
            rotation={[0, 0, 0.04]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 4"
          position={[2184.93, 595.17, 177.68]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.52]}
        >
          <mesh
            name="Cylinder 47"
            geometry={nodes['Cylinder 47'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 37"
            geometry={nodes['Cylinder 37'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 27"
            geometry={nodes['Cylinder 27'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder7"
            geometry={nodes.Cylinder7.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 3"
          position={[-224.79, 569.31, 8.49]}
          rotation={[-0.06, 0, 0]}
          scale={[-0.52, 1.01, 0.52]}
        >
          <mesh
            name="Cylinder 48"
            geometry={nodes['Cylinder 48'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 38"
            geometry={nodes['Cylinder 38'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[40.83, 69.72, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 28"
            geometry={nodes['Cylinder 28'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder8"
            geometry={nodes.Cylinder8.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree 2"
          position={[-169.25, 323.96, 219.95]}
          rotation={[0.07, 0, 0.05]}
          scale={[0.68, 0.77, 0.68]}
        >
          <mesh
            name="Cylinder 49"
            geometry={nodes['Cylinder 49'].geometry}
            material={materials.trunk}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 39"
            geometry={nodes['Cylinder 39'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[-12.23, 47.39, 0]}
            rotation={[0, 0, -0.01]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 29"
            geometry={nodes['Cylinder 29'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[-11.83, -116.7, 0]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder9"
            geometry={nodes.Cylinder9.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[-10.06, -271.33, 0]}
            rotation={[0, 0, 0.04]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <group
          name="tree"
          position={[503.86, 272.46, 170.64]}
          rotation={[3.12, 0.29, -3.1]}
          scale={[0.42, 0.48, 0.42]}
        >
          <mesh
            name="Cylinder 410"
            geometry={nodes['Cylinder 410'].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-0.91, -207.57, 1.19]}
            scale={[0.21, 0.85, 0.21]}
          />
          <mesh
            name="Cylinder 310"
            geometry={nodes['Cylinder 310'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[52.02, 70.54, 0]}
            rotation={[0, 0, -0.21]}
            scale={[1.04, 0.74, 1.04]}
          />
          <mesh
            name="Cylinder 210"
            geometry={nodes['Cylinder 210'].geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[23.04, -93.02, 0]}
            rotation={[0, 0, -0.13]}
            scale={[1.2, 0.84, 1.2]}
          />
          <mesh
            name="Cylinder10"
            geometry={nodes.Cylinder10.geometry}
            material={materials['tree yellow 2']}
            castShadow
            receiveShadow
            position={[6.46, -272.47, 0]}
            rotation={[0, 0, -0.05]}
            scale={[1.27, 0.89, 1.27]}
          />
        </group>
        <mesh
          name="Plane 2"
          geometry={nodes['Plane 2'].geometry}
          material={materials['Plane 2 Material']}
          castShadow
          receiveShadow
          position={[3, 0, 14.81]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials['Plane Material']}
          castShadow
          receiveShadow
          position={[52.5, -0.2, -420.5]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cube 20"
          geometry={nodes['Cube 20'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[17, 49.89, -106.55]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          name="Shape 28"
          geometry={nodes['Shape 28'].geometry}
          material={materials.blue3}
          castShadow
          receiveShadow
          position={[-144.15, 0.88, -113.78]}
          rotation={[-1.54, 0, 0]}
        />
        <mesh
          name="Shape 27"
          geometry={nodes['Shape 27'].geometry}
          material={materials['Shape 27 Material']}
          castShadow
          receiveShadow
          position={[-148.54, -90.22, -78.65]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 26"
          geometry={nodes['Shape 26'].geometry}
          material={materials.blue3}
          castShadow
          receiveShadow
          position={[162.32, 0, -155.7]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 25"
          geometry={nodes['Shape 25'].geometry}
          material={materials['Shape 25 Material']}
          castShadow
          receiveShadow
          position={[277.34, -90.24, 167.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 24"
          geometry={nodes['Shape 24'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[180.41, 0, -1.52]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 23"
          geometry={nodes['Shape 23'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[312.76, 0, 1.29]}
          rotation={[-Math.PI / 2, 0, -0.04]}
          scale={[1, 0.96, 1]}
        />
        <mesh
          name="Shape 22"
          geometry={nodes['Shape 22'].geometry}
          material={materials['Shape 22 Material']}
          castShadow
          receiveShadow
          position={[115.52, 269.18, -553.44]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 21"
          geometry={nodes['Shape 21'].geometry}
          material={materials['Shape 21 Material']}
          castShadow
          receiveShadow
          position={[207.81, 271.48, -569.88]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube 19"
          geometry={nodes['Cube 19'].geometry}
          material={materials['Cube 19 Material']}
          castShadow
          receiveShadow
          position={[272.9, 107.56, -150.37]}
          rotation={[-3.01, 1.56, 3.01]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 18"
          geometry={nodes['Cube 18'].geometry}
          material={materials['Cube 18 Material']}
          castShadow
          receiveShadow
          position={[272.8, 40.42, -150.72]}
          rotation={[1.57, 0, -1.59]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 17"
          geometry={nodes['Cube 17'].geometry}
          material={materials['Cube 17 Material']}
          castShadow
          receiveShadow
          position={[272.8, 83.21, -150.6]}
          rotation={[1.57, 0, -1.59]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 16"
          geometry={nodes['Cube 16'].geometry}
          material={materials['Cube 16 Material']}
          castShadow
          receiveShadow
          position={[272.8, 126.87, -150.49]}
          rotation={[1.57, 0, -1.59]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Shape 20"
          geometry={nodes['Shape 20'].geometry}
          material={materials.blue2}
          castShadow
          receiveShadow
          position={[-15.67, 273.27, -577.62]}
          rotation={[-Math.PI / 2, -0.01, 0]}
        />
        <mesh
          name="Shape 19"
          geometry={nodes['Shape 19'].geometry}
          material={materials.blue2}
          castShadow
          receiveShadow
          position={[-58.41, 272.27, -477.92]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 18"
          geometry={nodes['Shape 18'].geometry}
          material={materials['Shape 18 Material']}
          castShadow
          receiveShadow
          position={[-74.37, 271.42, -477.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 17"
          geometry={nodes['Shape 17'].geometry}
          material={materials.blue2}
          castShadow
          receiveShadow
          position={[189.94, 271, -19.91]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 16"
          geometry={nodes['Shape 16'].geometry}
          material={materials['Shape 16 Material']}
          castShadow
          receiveShadow
          position={[109.83, 270.44, -144.09]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 15"
          geometry={nodes['Shape 15'].geometry}
          material={materials['Shape 15 Material']}
          castShadow
          receiveShadow
          position={[-108.43, 270.52, -143.26]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 14"
          geometry={nodes['Shape 14'].geometry}
          material={materials.blue2}
          castShadow
          receiveShadow
          position={[-160.41, 269.91, -56.76]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube 15"
          geometry={nodes['Cube 15'].geometry}
          material={materials['Cube 15 Material']}
          castShadow
          receiveShadow
          position={[-37.08, 175.21, -187.42]}
          rotation={[1.58, 0, -0.19]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 14"
          geometry={nodes['Cube 14'].geometry}
          material={materials['Cube 14 Material']}
          castShadow
          receiveShadow
          position={[9.52, 176.86, -230.1]}
          rotation={[1.58, 0, -0.19]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 13"
          geometry={nodes['Cube 13'].geometry}
          material={materials['Cube 13 Material']}
          castShadow
          receiveShadow
          position={[70.13, 176.2, -265.62]}
          rotation={[1.57, 0, -0.38]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 12"
          geometry={nodes['Cube 12'].geometry}
          material={materials['Cube 12 Material']}
          castShadow
          receiveShadow
          position={[140.39, 177.52, -298.46]}
          rotation={[1.57, 0, -0.46]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 11"
          geometry={nodes['Cube 11'].geometry}
          material={materials['Cube 11 Material']}
          castShadow
          receiveShadow
          position={[63.02, 177.28, -293.56]}
          rotation={[1.57, 0, -2.55]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 10"
          geometry={nodes['Cube 10'].geometry}
          material={materials['Cube 10 Material']}
          castShadow
          receiveShadow
          position={[103.74, 176.51, -260.03]}
          rotation={[1.57, 0, -2.45]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 9"
          geometry={nodes['Cube 9'].geometry}
          material={materials['Cube 9 Material']}
          castShadow
          receiveShadow
          position={[170.3, 176.2, -227.8]}
          rotation={[1.57, 0, -2.45]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 8"
          geometry={nodes['Cube 8'].geometry}
          material={materials['Cube 8 Material']}
          castShadow
          receiveShadow
          position={[232.92, 177.07, -194.86]}
          rotation={[1.57, 0, -2.45]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 7"
          geometry={nodes['Cube 7'].geometry}
          material={materials['Cube 7 Material']}
          castShadow
          receiveShadow
          position={[112.27, 178.95, -433.64]}
          rotation={[1.57, 0, -1.57]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 6"
          geometry={nodes['Cube 6'].geometry}
          material={materials['Cube 6 Material']}
          castShadow
          receiveShadow
          position={[110.76, 179.26, -367.28]}
          rotation={[1.57, 0, -1.57]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 5"
          geometry={nodes['Cube 5'].geometry}
          material={materials['Cube 5 Material']}
          castShadow
          receiveShadow
          position={[106.63, 178.84, -227.4]}
          rotation={[1.57, 0, -1.57]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 4"
          geometry={nodes['Cube 4'].geometry}
          material={materials['Cube 4 Material']}
          castShadow
          receiveShadow
          position={[109.56, 179.85, -297.07]}
          rotation={[1.57, 0, -1.57]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube 3"
          geometry={nodes['Cube 3'].geometry}
          material={materials['Cube 3 Material']}
          castShadow
          receiveShadow
          position={[13.33, 177.11, -342.24]}
          rotation={[1.57, 0, 0.51]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Shape 13"
          geometry={nodes['Shape 13'].geometry}
          material={materials.blue}
          castShadow
          receiveShadow
          position={[84.21, 0, -478.86]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 12"
          geometry={nodes['Shape 12'].geometry}
          material={materials['Shape 12 Material']}
          castShadow
          receiveShadow
          position={[83.74, -106.54, -479.11]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube 2"
          geometry={nodes['Cube 2'].geometry}
          material={materials['Cube 2 Material']}
          castShadow
          receiveShadow
          position={[207.66, 177.55, -340.72]}
          rotation={[1.57, 0, -0.46]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials['Cube Material']}
          castShadow
          receiveShadow
          position={[105.09, 173.78, -154.25]}
          rotation={[1.57, 0, -1.58]}
          scale={[1, 1, 1.41]}
        />
        <mesh
          name="Shape 11"
          geometry={nodes['Shape 11'].geometry}
          material={materials.blue}
          castShadow
          receiveShadow
          position={[-97.19, 0, -150.8]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 10"
          geometry={nodes['Shape 10'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[388.66, 0, -410.44]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 9"
          geometry={nodes['Shape 9'].geometry}
          material={materials['Shape 9 Material']}
          castShadow
          receiveShadow
          position={[387.23, 3.12, -386.57]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 8"
          geometry={nodes['Shape 8'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[279.02, 0, -373.57]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 7"
          geometry={nodes['Shape 7'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[376.36, -0.2, -613.28]}
          rotation={[-1.55, 0, 0.02]}
        />
        <mesh
          name="Shape 6"
          geometry={nodes['Shape 6'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[113.32, -1.28, -564.58]}
          rotation={[-1.55, 0, 0.02]}
        />
        <mesh
          name="Shape 5"
          geometry={nodes['Shape 5'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[383.53, -1.59, -2.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Shape 4"
          geometry={nodes['Shape 4'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[-83.64, 87, -478.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Pentagon"
          geometry={nodes.Pentagon.geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[-1.02, 1, -477]}
          rotation={[-Math.PI / 2, 0, -1.57]}
        />
        <mesh
          name="Shape 3"
          geometry={nodes['Shape 3'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[-195.95, 86.99, -0.11]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          name="Shape 2"
          geometry={nodes['Shape 2'].geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[312.91, 85.79, -0.66]}
          rotation={[-Math.PI / 2, 0, 0.03]}
        />
        <mesh
          name="Shape"
          geometry={nodes.Shape.geometry}
          material={materials.stone1}
          castShadow
          receiveShadow
          position={[-340.57, 0, -0.41]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        {/* <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={2500}
          shadow-camera-left={-1250}
          shadow-camera-right={1250}
          shadow-camera-top={1250}
          shadow-camera-bottom={-1250}
          position={[31, 387, 261]}
        /> */}
        {/* <OrthographicCamera
          name="Personal Camera"
          makeDefault={true}
          zoom={0.32}
          far={100000}
          near={-100000}
          position={[498.61, 886.12, 1569.05]}
          rotation={[-0.4, 0.26, 0.11]}
        /> */}
        {/* <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
          position={[0, 1, 0]}
        /> */}
      </group>
    </>
  );
}
