/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';

export default function Centerpiece({ ...props }) {
  const { nodes, materials } = useSpline(
    'https://prod.spline.design/K3nNIphDhCa-VsHG/scene.splinecode'
  );
  return (
    <>
      <color attach="background" args={['#4b4d52']} />
      <group {...props} dispose={null}>
        <mesh
          name="Cube 41"
          geometry={nodes['Cube 41'].geometry}
          material={materials['Cube 41 Material']}
          castShadow
          receiveShadow
          position={[-2061.04, 500, -2193.87]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 40"
          geometry={nodes['Cube 40'].geometry}
          material={materials['Cube 40 Material']}
          castShadow
          receiveShadow
          position={[-2063.99, 500, -1780.07]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 39"
          geometry={nodes['Cube 39'].geometry}
          material={materials['Cube 39 Material']}
          castShadow
          receiveShadow
          position={[-2063.99, 500, -1409.87]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 38"
          geometry={nodes['Cube 38'].geometry}
          material={materials['Cube 38 Material']}
          castShadow
          receiveShadow
          position={[-2063.99, 500, -1037.04]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 37"
          geometry={nodes['Cube 37'].geometry}
          material={materials['Cube 37 Material']}
          castShadow
          receiveShadow
          position={[-2063.99, 500, -646.88]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 36"
          geometry={nodes['Cube 36'].geometry}
          material={materials['Cube 36 Material']}
          castShadow
          receiveShadow
          position={[-2063.99, 500, -213.05]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 35"
          geometry={nodes['Cube 35'].geometry}
          material={materials['Cube 35 Material']}
          castShadow
          receiveShadow
          position={[-2082, 500, 213]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 34"
          geometry={nodes['Cube 34'].geometry}
          material={materials['Cube 34 Material']}
          castShadow
          receiveShadow
          position={[-1421.28, -4.71, -3304.32]}
          rotation={[0, -2.09, 0]}
          scale={0.5}
        />
        <mesh
          name="Pyramid 5"
          geometry={nodes['Pyramid 5'].geometry}
          material={materials.triangle}
          castShadow
          receiveShadow
          position={[617, 153.28, -2077]}
          rotation={[0, 0.61, 0]}
        />
        <mesh
          name="Pyramid 4"
          geometry={nodes['Pyramid 4'].geometry}
          material={materials.triangle}
          castShadow
          receiveShadow
          position={[19, 153.28, -1218.33]}
          rotation={[0, 0.16, 0]}
        />
        <mesh
          name="Pyramid 3"
          geometry={nodes['Pyramid 3'].geometry}
          material={materials.triangle}
          castShadow
          receiveShadow
          position={[1181.14, 338.04, 1381.82]}
          rotation={[-0.02, -1.28, -0.03]}
        />
        <mesh
          name="Pyramid 2"
          geometry={nodes['Pyramid 2'].geometry}
          material={materials.triangle}
          castShadow
          receiveShadow
          position={[2651.44, 604.32, -374.29]}
          rotation={[3.1, 1.39, -3.09]}
        />
        <mesh
          name="Pyramid"
          geometry={nodes.Pyramid.geometry}
          material={materials.triangle}
          castShadow
          receiveShadow
          position={[-560.37, 153.28, 2157.31]}
          rotation={[0, -0.08, 0]}
        />
        <mesh
          name="Ellipse"
          geometry={nodes.Ellipse.geometry}
          material={materials['Ellipse Material']}
          castShadow
          receiveShadow
          position={[-2075.6, 0, -838.26]}
          rotation={[-Math.PI / 2, 0, -1.61]}
        />
        <mesh
          name="Cube 33"
          geometry={nodes['Cube 33'].geometry}
          material={materials['Cube 33 Material']}
          castShadow
          receiveShadow
          position={[-1388.46, 0, 862.16]}
          rotation={[0, -0.39, 0]}
          scale={0.5}
        />
        <mesh
          name="Cube 32"
          geometry={nodes['Cube 32'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[4991, 0, -995]}
          scale={0.5}
        />
        <mesh
          name="Cube 31"
          geometry={nodes['Cube 31'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[4131, 0, -2874]}
          scale={0.5}
        />
        <mesh
          name="Cube 30"
          geometry={nodes['Cube 30'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[4604.96, 0, -1931.08]}
          scale={0.5}
        />
        <mesh
          name="Cube 29"
          geometry={nodes['Cube 29'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[1070, 0, -4740.92]}
          scale={0.5}
        />
        <mesh
          name="Cube 28"
          geometry={nodes['Cube 28'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[2782, 0, -4024.96]}
          scale={0.5}
        />
        <mesh
          name="Cube 27"
          geometry={nodes['Cube 27'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[1970, 0, -4427.15]}
          scale={0.5}
        />
        <mesh
          name="Cube 26"
          geometry={nodes['Cube 26'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-1005, 0, -4905]}
          scale={0.5}
        />
        <mesh
          name="Cube 24"
          geometry={nodes['Cube 24'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-4122.33, 0, -2726.36]}
          scale={0.5}
        />
        <mesh
          name="Cube 23"
          geometry={nodes['Cube 23'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-4912.33, 0, -1016.51]}
          scale={0.5}
        />
        <mesh
          name="Cube 22"
          geometry={nodes['Cube 22'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-1979, 0, -4580]}
          scale={0.5}
        />
        <mesh
          name="Cube 21"
          geometry={nodes['Cube 21'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-4597.33, 0, -1931.96]}
          scale={0.5}
        />
        <mesh
          name="Cube 20"
          geometry={nodes['Cube 20'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[1107, 0, 4905]}
          scale={0.5}
        />
        <mesh
          name="Cube 19"
          geometry={nodes['Cube 19'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[2849, 0, 4115]}
          scale={0.5}
        />
        <mesh
          name="Cube 18"
          geometry={nodes['Cube 18'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[4952, 0, 984]}
          scale={0.5}
        />
        <mesh
          name="Cube 17"
          geometry={nodes['Cube 17'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[4186, 0, 2717]}
          scale={0.5}
        />
        <mesh
          name="Cube 16"
          geometry={nodes['Cube 16'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[4687, 0, 1925]}
          scale={0.5}
        />
        <mesh
          name="Cube 15"
          geometry={nodes['Cube 15'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[2091, 0, 4572]}
          scale={0.5}
        />
        <mesh
          name="Cube 14"
          geometry={nodes['Cube 14'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-1035, 0, 4928]}
          scale={0.5}
        />
        <mesh
          name="Cube 12"
          geometry={nodes['Cube 12'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-1951, 0, 4572]}
          scale={0.5}
        />
        <mesh
          name="Cube 11"
          geometry={nodes['Cube 11'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-4895.33, 0, 886]}
          scale={0.5}
        />
        <mesh
          name="Cube 10"
          geometry={nodes['Cube 10'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-4145.33, 0, 2717]}
          scale={0.5}
        />
        <mesh
          name="Cube 9"
          geometry={nodes['Cube 9'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-4597.33, 0, 1849]}
          scale={0.5}
        />
        <mesh
          name="Cube 8"
          geometry={nodes['Cube 8'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[3535, 0, -3536]}
          scale={0.5}
        />
        <mesh
          name="Cube 7"
          geometry={nodes['Cube 7'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-3535, 0, -3502]}
          scale={0.5}
        />
        <mesh
          name="Cube 6"
          geometry={nodes['Cube 6'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-3535, 0, 3535]}
          scale={0.5}
        />
        <mesh
          name="Cube 5"
          geometry={nodes['Cube 5'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[3560, 0, 3495]}
          scale={0.5}
        />
        <mesh
          name="Cube 4"
          geometry={nodes['Cube 4'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[0, 0, -5000]}
          scale={0.5}
        />
        <mesh
          name="Cube 3"
          geometry={nodes['Cube 3'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[5000, 0, 0]}
          scale={0.5}
        />
        <mesh
          name="Cube 2"
          geometry={nodes['Cube 2'].geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[0, 0, 5000]}
          scale={0.5}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials.pole}
          castShadow
          receiveShadow
          position={[-5000, 0, 0]}
          scale={0.5}
        />
        {/* <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={2500}
          shadow-camera-left={-1250}
          shadow-camera-right={1250}
          shadow-camera-top={1250}
          shadow-camera-bottom={-1250}
          position={[-1102.4, 2171.38, 300]}
          rotation={[0, 0, 0.92]}
        />
        <OrthographicCamera
          name="Personal Camera"
          makeDefault={true}
          zoom={0.04}
          far={100000}
          near={-100000}
          up={[0, -1, 0]}
          position={[-1.4, 993.21, -116.35]}
          rotation={[-1.69, 0, 0.01]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} /> */}
      </group>
    </>
  );
}
